input_dir = "data/eu-email/"
nfa_dir = "data/nfa/nfa-3-connected.csv"
debug =    0 # 0  For nothing - 10 for everything
pattern_type = "path2"
    #"triangles_WOJ"
    #"rectangle_woj"
    #"path2"
    #"path3"
    #"path4"


pattern_size = 3
#nfa_size = 2